[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta"


[tool.cibuildwheel]
test-requires = ["pytest", "tqdm", "tifffile"]
test-command = "pytest {project}/tests"
#skip="pp37-macos*"
skip="pp*"
