[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy"]

[tool.cibuildwheel]
test-requires = ["pytest", "tqdm", "tifffile"]
test-command = "pytest {project}/tests"
#skip="pp37-macos*"
skip="pp*"
